### ISSUE TITLE
i got this problem in flask

### ISSUE THREAD

**Issue by Anzigar** [ihiji/falcon-marshmallow#20]
/2023 17:02:33] "POST /api/workouts HTTP/1.1" 500 -
[2023-03-07 17:03:04,784] ERROR in app: Exception on /api/workouts [POST]
Traceback (most recent call last):
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask/views.py", line 107, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/Users/ansi/Downloads/journeybackend-main/routes.py", line 178, in post
    workout_data = workout_schema.load(workout_json)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow_sqlalchemy/load_instance_mixin.py", line 96, in load
    return super().load(data, **kwargs)
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow/schema.py", line 722, in load
    return self._do_load(
  File "/Users/ansi/Desktop/PROJECTS/journeybackend/env/lib/python3.10/site-packages/marshmallow/schema.py", line 909, in _do_load
    raise exc
marshmallow.exceptions.ValidationError: {'total_time': ['Missing data for required field.'], 'total_time ': ['Unknown field.']}
192.168.206.79 - - [07/Mar/2023 17:03:04] "POST /api/workouts HTTP/1.1" 500 -

**Comment by Anzigar** [comment]
this is my codes

        
        
#workout-schema
class WorkoutSchema(ma.SQLAlchemyAutoSchema):
    class Meta:
        model = Workout
        include_fk = True
        load_instance = True
